python runSelection.py -j 0
python runSelection.py -j 1
python runSelection.py -j 2
python runSelection.py -j 3
python runSelection.py -j 4
python runSelection.py -j 5
python runSelection.py -j 6
python runSelection.py -j 7
python runSelection.py -j 8
python runSelection.py -j 9
python runSelection.py -j 10
python runSelection.py -j 11
python runSelection.py -j 12
python runSelection.py -j 13
python runSelection.py -j 14
python runSelection.py -j 15
python runSelection.py -j 16
python runSelection.py -j 17
python runSelection.py -j 18
python runSelection.py -j 19
python runSelection.py -j 20
python runSelection.py -j 21
python runSelection.py -j 22
python runSelection.py -j 23
python runSelection.py -j 24
python runSelection.py -j 25
python runSelection.py -j 26
python runSelection.py -j 27
python runSelection.py -j 28
python runSelection.py -j 29
python runSelection.py -j 30
python runSelection.py -j 31
python runSelection.py -j 32
python runSelection.py -j 33
python runSelection.py -j 34
python runSelection.py -j 35
python runSelection.py -j 36
python runSelection.py -j 37
python runSelection.py -j 38
python runSelection.py -j 39
python runSelection.py -j 40
python runSelection.py -j 41
python runSelection.py -j 42
python runSelection.py -j 43
python runSelection.py -j 44
python runSelection.py -j 45
python runSelection.py -j 46
python runSelection.py -j 47
python runSelection.py -j 48
python runSelection.py -j 49
python runSelection.py -j 50
python runSelection.py -j 51
python runSelection.py -j 52
python runSelection.py -j 53
python runSelection.py -j 54
python runSelection.py -j 55
python runSelection.py -j 56
python runSelection.py -j 57
python runSelection.py -j 58
python runSelection.py -j 59
python runSelection.py -j 60
python runSelection.py -j 61
python runSelection.py -j 62
python runSelection.py -j 63
python runSelection.py -j 64
python runSelection.py -j 65
python runSelection.py -j 66
python runSelection.py -j 67
python runSelection.py -j 68
python runSelection.py -j 69
python runSelection.py -j 70
python runSelection.py -j 71
python runSelection.py -j 72
python runSelection.py -j 73
python runSelection.py -j 74
python runSelection.py -j 75
python runSelection.py -j 76
python runSelection.py -j 77
python runSelection.py -j 78
python runSelection.py -j 79
python runSelection.py -j 80
python runSelection.py -j 81
python runSelection.py -j 82
python runSelection.py -j 83
python runSelection.py -j 84
python runSelection.py -j 85
python runSelection.py -j 86
python runSelection.py -j 87
python runSelection.py -j 88
python runSelection.py -j 89
python runSelection.py -j 90
python runSelection.py -j 91
python runSelection.py -j 92
python runSelection.py -j 93
python runSelection.py -j 94
python runSelection.py -j 95
python runSelection.py -j 96
python runSelection.py -j 97
python runSelection.py -j 98
python runSelection.py -j 99
python runSelection.py -j 100
python runSelection.py -j 101
python runSelection.py -j 102
python runSelection.py -j 103
python runSelection.py -j 104
python runSelection.py -j 105
python runSelection.py -j 106
python runSelection.py -j 107
python runSelection.py -j 108
python runSelection.py -j 109
python runSelection.py -j 110
python runSelection.py -j 111
python runSelection.py -j 112
python runSelection.py -j 113
python runSelection.py -j 114
python runSelection.py -j 115
python runSelection.py -j 116
python runSelection.py -j 117
python runSelection.py -j 118
python runSelection.py -j 119
python runSelection.py -j 120
python runSelection.py -j 121
python runSelection.py -j 122
python runSelection.py -j 123
python runSelection.py -j 124
python runSelection.py -j 125
python runSelection.py -j 126
python runSelection.py -j 127
python runSelection.py -j 128
python runSelection.py -j 129
python runSelection.py -j 130
python runSelection.py -j 131
python runSelection.py -j 132
python runSelection.py -j 133
python runSelection.py -j 134
python runSelection.py -j 135
python runSelection.py -j 136
python runSelection.py -j 137
python runSelection.py -j 138
python runSelection.py -j 139
python runSelection.py -j 140
python runSelection.py -j 141
python runSelection.py -j 142
python runSelection.py -j 143
python runSelection.py -j 144
python runSelection.py -j 145
python runSelection.py -j 146
python runSelection.py -j 147
python runSelection.py -j 148
python runSelection.py -j 149
python runSelection.py -j 150
python runSelection.py -j 151
python runSelection.py -j 152
python runSelection.py -j 153
python runSelection.py -j 154
python runSelection.py -j 155
python runSelection.py -j 156
python runSelection.py -j 157
python runSelection.py -j 158
python runSelection.py -j 159
python runSelection.py -j 160
python runSelection.py -j 161
python runSelection.py -j 162
python runSelection.py -j 163
python runSelection.py -j 164
python runSelection.py -j 165
python runSelection.py -j 166
python runSelection.py -j 167
python runSelection.py -j 168
python runSelection.py -j 169
python runSelection.py -j 170
python runSelection.py -j 171
python runSelection.py -j 172
python runSelection.py -j 173
python runSelection.py -j 174
python runSelection.py -j 175
python runSelection.py -j 176
python runSelection.py -j 177
python runSelection.py -j 178
python runSelection.py -j 179
python runSelection.py -j 180
python runSelection.py -j 181
python runSelection.py -j 182
python runSelection.py -j 183
python runSelection.py -j 184
python runSelection.py -j 185
python runSelection.py -j 186
python runSelection.py -j 187
python runSelection.py -j 188
python runSelection.py -j 189
python runSelection.py -j 190
python runSelection.py -j 191
python runSelection.py -j 192
python runSelection.py -j 193
python runSelection.py -j 194
python runSelection.py -j 195
python runSelection.py -j 196
python runSelection.py -j 197
python runSelection.py -j 198
python runSelection.py -j 199
python runSelection.py -j 200
python runSelection.py -j 201
python runSelection.py -j 202
python runSelection.py -j 203
python runSelection.py -j 204
python runSelection.py -j 205
python runSelection.py -j 206
python runSelection.py -j 207
python runSelection.py -j 208
python runSelection.py -j 209
python runSelection.py -j 210
python runSelection.py -j 211
python runSelection.py -j 212
python runSelection.py -j 213
python runSelection.py -j 214
python runSelection.py -j 215
python runSelection.py -j 216
python runSelection.py -j 217
python runSelection.py -j 218
python runSelection.py -j 219
python runSelection.py -j 220
python runSelection.py -j 221
python runSelection.py -j 222
python runSelection.py -j 223
python runSelection.py -j 224
python runSelection.py -j 225
python runSelection.py -j 226
python runSelection.py -j 227
python runSelection.py -j 228
python runSelection.py -j 229
python runSelection.py -j 230
python runSelection.py -j 231
python runSelection.py -j 232
python runSelection.py -j 233
python runSelection.py -j 234
python runSelection.py -j 235
python runSelection.py -j 236
python runSelection.py -j 237
python runSelection.py -j 238
python runSelection.py -j 239
python runSelection.py -j 240
python runSelection.py -j 241
python runSelection.py -j 242
python runSelection.py -j 243
python runSelection.py -j 244
python runSelection.py -j 245
python runSelection.py -j 246
python runSelection.py -j 247
python runSelection.py -j 248
python runSelection.py -j 249
python runSelection.py -j 250
python runSelection.py -j 251
python runSelection.py -j 252
python runSelection.py -j 253
python runSelection.py -j 254
python runSelection.py -j 255
python runSelection.py -j 256
python runSelection.py -j 257
python runSelection.py -j 258
python runSelection.py -j 259
python runSelection.py -j 260
python runSelection.py -j 261
python runSelection.py -j 262
python runSelection.py -j 263
python runSelection.py -j 264
python runSelection.py -j 265
python runSelection.py -j 266
python runSelection.py -j 267
python runSelection.py -j 268
python runSelection.py -j 269
python runSelection.py -j 270
python runSelection.py -j 271
python runSelection.py -j 272
python runSelection.py -j 273
python runSelection.py -j 274
python runSelection.py -j 275
python runSelection.py -j 276
python runSelection.py -j 277
python runSelection.py -j 278
python runSelection.py -j 279
python runSelection.py -j 280
python runSelection.py -j 281
python runSelection.py -j 282
python runSelection.py -j 283
python runSelection.py -j 284
python runSelection.py -j 285
python runSelection.py -j 286
python runSelection.py -j 287
python runSelection.py -j 288
python runSelection.py -j 289
python runSelection.py -j 290
python runSelection.py -j 291
python runSelection.py -j 292
python runSelection.py -j 293
python runSelection.py -j 294
python runSelection.py -j 295
python runSelection.py -j 296
python runSelection.py -j 297
python runSelection.py -j 298
python runSelection.py -j 299
python runSelection.py -j 300
python runSelection.py -j 301
python runSelection.py -j 302
python runSelection.py -j 303
python runSelection.py -j 304
python runSelection.py -j 305
python runSelection.py -j 306
python runSelection.py -j 307
python runSelection.py -j 308
python runSelection.py -j 309
python runSelection.py -j 310
python runSelection.py -j 311
python runSelection.py -j 312
python runSelection.py -j 313
python runSelection.py -j 314
python runSelection.py -j 315
python runSelection.py -j 316
python runSelection.py -j 317
python runSelection.py -j 318
python runSelection.py -j 319
python runSelection.py -j 320
python runSelection.py -j 321
python runSelection.py -j 322
python runSelection.py -j 323
python runSelection.py -j 324
python runSelection.py -j 325
python runSelection.py -j 326
python runSelection.py -j 327
python runSelection.py -j 328
python runSelection.py -j 329
python runSelection.py -j 330
python runSelection.py -j 331
python runSelection.py -j 332
python runSelection.py -j 333
python runSelection.py -j 334
python runSelection.py -j 335
