# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget HighFive libheaders libdeps)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target HighFive
add_library(HighFive INTERFACE IMPORTED)

set_target_properties(HighFive PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MPI_NO_CPPBIND"
  INTERFACE_LINK_LIBRARIES "libheaders;libdeps"
)

# Create imported target libheaders
add_library(libheaders INTERFACE IMPORTED)

set_target_properties(libheaders PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/gilson/Dropbox/HEP/HEPHero/include/HighFive/include"
)

# Create imported target libdeps
add_library(libdeps INTERFACE IMPORTED)

set_target_properties(libdeps PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB;H5_USE_BOOST"
  INTERFACE_INCLUDE_DIRECTORIES "/cvmfs/sft.cern.ch/lcg/releases/hdf5/1.10.6-a3b1e/x86_64-centos7-gcc9-opt/include;/cvmfs/sft.cern.ch/lcg/releases/zlib/1.2.11-8af4c/x86_64-centos7-gcc9-opt/include;/usr/include;/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc9-opt/include"
  INTERFACE_LINK_LIBRARIES "/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc9-opt/lib/libhdf5.so;/usr/lib64/libpthread.so;/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc9-opt/lib/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so"
)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
